// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL if present; otherwise fall back to Neon example from user.
    url:
      process.env["DATABASE_URL"] ||
      "postgresql://neondb_owner:npg_z58wMFDRWShd@ep-spring-frost-awiuxisk-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});

